services:
  tech-new-writer:
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-new-writer:latest
    env_file:
      - .env
    working_dir: /app
    command: python -m uvicorn tech_new_writer.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: "no"
